name: Datastore Emulator

on: 
    push:
        branches:
            - master

jobs:
    emulator:
        runs-on: ubuntu-latest
        # container:
        #   image: marcosj/datastore-emulator:ubuntu
        #   env:
        #     CLOUDSDK_CORE_PROJECT: hds-dev  
        env:
            CLOUDSDK_CORE_PROJECT: hds-dev
        services:
            datastore-emulator:
                image: marcosj/datastore-emulator:ubuntu
                ports:
                    - 8081:8081
                env:
                    CLOUDSDK_CORE_PROJECT: hds-dev
        steps:
            - name: Test
              run: curl -l 127.0.0.1:8081
