name: Datastore Emulator
on: 
    push:
        branches:
            - master

jobs:
    emulator:
        runs-on: ubuntu-latest
        env:
            CLOUDSDK_CORE_PROJECT: hds-dev
            CLOUDSDK_VERSION: 458.0.1
            CLOUDSDK_ARCH: x86_64
        steps:
            - name: Cache dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: google-cloud-sdk
                key: deps-gcloud
            - name: Install Google Cloud SDK
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
                curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-458.0.1-linux-x86_64.tar.gz
                tar -xf google-cloud-cli-458.0.1-linux-x86_64.tar.gz
                ./google-cloud-sdk/install.sh --quiet --usage-reporting false --path-update true --command-completion true
                ./google-cloud-sdk/bin/gcloud components install beta cloud-datastore-emulator --quiet
            - name: Run Emulator
              run: ./google-cloud-sdk/bin/gcloud beta emulators datastore start --project=hds-dev --no-store-on-disk --use-firestore-in-datastore-mode --host-port=0.0.0.0:8081 &
            - name: Test
              run: curl localhost:8081

            #   - name: Install dependencies
            #   run: |
            #     sudo apt-get update -y 
            #     sudo apt-get install --yes --no-install-recommends default-jre
