name: Datastore Emulator
on: 
    push:
        branches:
            - master

jobs:
    emulator:
        runs-on: ubuntu-latest
        env:
            CLOUDSDK_CORE_PROJECT: hds-dev
        steps:
            - name: Install emulator
              run: |
                gcloud components install beta cloud-datastore-emulator --quiet
            - name: Run Emulator
              run: gcloud beta emulators datastore start
            - name: Test
              run: echo "running tests"
