name: Datastore Emulator

on: 
    push:
        branches:
            - master

jobs:
    emulator:
        runs-on: ubuntu-latest
        container:
          image: marcosj/datastore-emulator:ubuntu
        env:
            CLOUDSDK_CORE_PROJECT: hds-dev
        steps:
            - name: Test
              run: curl -l localhost:8081
