name: Datastore Emulator
on: 
    push:
        branches:
            - master

jobs:
    emulator:
        runs-on: ubuntu-latest
        steps:
            - name: Install emulator
              run: |
                sudo apt-get -y update
                sudo apt-get install -y google-cloud-sdk-datastore-emulator
            - name: Run Emulator
              run: gcloud beta emulators datastore start
            - name: Test
              run: echo "running tests"
